"use client"
import { useEffect, useState } from "react"
import { useParams } from "next/navigation"
import { motion } from "framer-motion"
import Link from "next/link"
import { ArrowLeft, FileText, BookOpen, Sparkles, Copy, Check, ChevronDown } from "lucide-react"
import { supabase } from "@/lib/supabase"

export default function LiteraturePage() {
  const { id } = useParams()
  const [paper, setPaper] = useState<any>(null)
  const [allPapers, setAllPapers] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [topic, setTopic] = useState("")
  const [selected, setSelected] = useState<string[]>([])
  const [generating, setGenerating] = useState(false)
  const [result, setResult] = useState("")
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const fetchData = async () => {
      const { data: p } = await supabase.from("papers").select("*").eq("id", id).single()
      setPaper(p)
      if (p) setSelected([p.id])

      const { data: all } = await supabase.from("papers").select("id, title, file_name").order("created_at", { ascending: false })
      setAllPapers(all || [])
      setLoading(false)
    }
    fetchData()
  }, [id])

  const toggleSelect = (paperId: string) => {
    setSelected(prev =>
      prev.includes(paperId) ? prev.filter(x => x !== paperId) : [...prev, paperId]
    )
  }

  const handleGenerate = async () => {
    if (!topic.trim()) return
    setGenerating(true)
    // Backend connect hone ke baad real AI response aayega
    setTimeout(() => {
      setResult(`Literature Review: ${topic}\n\nThis literature review will be generated by AI once the backend is connected. It will include:\n\n1. Introduction\n2. Related Work\n3. Research Trends\n4. Research Gaps\n5. Conclusion\n\nBased on ${selected.length} selected paper(s).`)
      setGenerating(false)
    }, 2000)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(result)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-6 h-6 border-2 border-[#00C853] border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <div className="p-5 md:p-8 max-w-3xl mx-auto space-y-6">

      <Link href={`/dashboard/papers/${id}`} className="inline-flex items-center gap-2 text-gray-400 hover:text-white text-sm transition">
        <ArrowLeft className="w-4 h-4" />
        Back to Paper
      </Link>

      <div>
        <div className="flex items-center gap-2 mb-1">
          <BookOpen className="w-5 h-5 text-[#00C853]" />
          <h1 className="text-2xl font-bold text-white">Literature Review</h1>
        </div>
        <p className="text-gray-500 text-sm">Generate a comprehensive literature review using your papers</p>
      </div>

      {/* Topic Input */}
      <div className="space-y-2">
        <label className="text-xs text-gray-400 uppercase tracking-wider font-medium">Research Topic</label>
        <input
          type="text"
          placeholder="e.g. Deep Learning in Healthcare, NLP for Text Classification..."
          value={topic}
          onChange={e => setTopic(e.target.value)}
          className="w-full bg-white/[0.04] border border-white/8 rounded-xl px-4 py-3 text-sm text-white placeholder:text-gray-600 outline-none focus:border-[#00C853]/40 transition"
        />
      </div>

      {/* Paper Selection */}
      <div className="space-y-2">
        <label className="text-xs text-gray-400 uppercase tracking-wider font-medium">
          Select Papers ({selected.length} selected)
        </label>
        <div className="space-y-2">
          {allPapers.map(p => (
            <button
              key={p.id}
              onClick={() => toggleSelect(p.id)}
              className={`w-full flex items-center gap-3 p-3 rounded-xl border text-left transition ${
                selected.includes(p.id)
                  ? "border-[#00C853]/40 bg-[#00C853]/5"
                  : "border-white/8 bg-white/[0.02] hover:border-white/15"
              }`}
            >
              <div className={`w-4 h-4 rounded border-2 flex items-center justify-center shrink-0 transition ${
                selected.includes(p.id) ? "bg-[#00C853] border-[#00C853]" : "border-white/20"
              }`}>
                {selected.includes(p.id) && <Check className="w-2.5 h-2.5 text-black" />}
              </div>
              <div className="w-7 h-7 rounded-lg bg-red-500/10 border border-red-500/20 flex items-center justify-center shrink-0">
                <FileText className="w-3.5 h-3.5 text-red-400" />
              </div>
              <span className="text-sm text-white truncate">{p.title || p.file_name}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Generate Button */}
      <button
        onClick={handleGenerate}
        disabled={!topic.trim() || selected.length === 0 || generating}
        className="w-full flex items-center justify-center gap-2 bg-[#00C853] hover:bg-[#00a844] disabled:opacity-40 text-black font-bold py-3 rounded-xl transition"
      >
        {generating ? (
          <>
            <div className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Generate Literature Review
          </>
        )}
      </button>

      {/* Result */}
      {result && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/[0.04] border border-white/8 rounded-xl overflow-hidden"
        >
          <div className="flex items-center justify-between px-4 py-3 border-b border-white/8">
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Generated Review</span>
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg transition ${
                copied ? "bg-[#00C853]/15 text-[#00C853]" : "bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white"
              }`}
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
          <div className="p-4">
            <p className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap">{result}</p>
          </div>
        </motion.div>
      )}

    </div>
  )
}